
"""

@author: Dr. Ruslan Sherstyukov, Sodankyla Geophysical Observatory, 2024

"""

import ModelsEvaluation


# Specify parameter and model for evaluation...
# parameters: "FOF2", "FOF1", "FOES", "FOE", "FBES", "FMIN", "HE", "HES", "HF"
parameter, model = "FOES","FOES"

# The output of the function, Evaluation_FOF2.csv, consists of GroundTruth, Predictions, Difference, MAE, and RMSE values.
ModelsEvaluation.Evaluate(parameter,model)

# Decide the ionogram_index from the relevant Evaluation_(FOF2/FOF1/FOE/FOES/FBES/FMIN/HE/HES/HF).csv file.
# The Evaluation_(FOF2/FOF1/FOE/FOES/FBES/FMIN/HE/HES/HF).csv file must be generated by the ModelsEvaluation.Evaluate(parameter, model) function.
# The output of the function is an ionogram_date.png image with the relevant GroundTruth and Prediction parameters.
ModelsEvaluation.IonogramShow(parameter, ionogram_index = 50)
